language: node_js
node_js:
  - 14
cache:
  yarn: true
  directories:
    - node_modules
    - '.cache'
script:
  - yarn build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: '$GITHUB_TOKEN'
  local_dir: dist
  on:
    branch: master
env:
  global:
    - secure: PEOdIigQkXTcnQSxkVkayl8lMDUcRQgVBnN4AthVpwhTEFlYJ1J1uwGov/JLgGTtDWKGLcIEyxmehcohYrG2xC7p79JHn2LPteFj7JF+fls2JmFYPq4wPXQ2OaebcGmx2ykpN7UoD1YSrmmCmVCHmezJ3/V/RKA4t1yhhctVjidGZ3e+itB6evP3gY8AuvDqlcFSjT5YMQZ1H67GvOwRHEWZruOZkb2/rOg5TH+UMElM1r7F0oQXhgeyb+dibQ+tJv5DUiDHcZa55ROPZGxQ88BSV3Wt9EzW2q0xUT25nZf3fo1nD0AO8zNKeaC6sDQzTWkZFdVxx8IMqC2J/QfpJ+ciMRvgj/uIysETvoFWj05UnWhwPNUqZgFVXxfSVLeHawzIh63qCoPsFmGy2T8sqsA25eBTB31+SL2mP0D1nOjzQNlbTuah2YzIZr1DaEQ9nEQ9wtVIj6SapdV6ROB+VQgREt9fNxkYSQe3o/vSZJ9srAm/s4qEZDbrFy1nGHxVoXKsMqKYT5i+UGiUgNUhAloIDPvjWlXq4pVWtrmS9i+Nj/fblG5XLrUNWpfcrl2Qt8X02jsYYgp54grkmc1H+E7Vj/gZPyCiD3AZaBPpcrD+Kh4X38RlU4DgTxOLc6HwB1payXPHwZLdP4StgYHwJ2y8CWiUsc4bfy6efsqLCxI=
